### ISSUE TITLE
Unable To Build Project

### ISSUE THREAD

**Issue by firefinchdev** [coding-blocks/ide#169]
On running ```npm install``` and then ```npm run dev```, the follwing error occurs:
```anirudh@anirudh-Vostro-3558:~/ide$ npm run dev

> cb-ide@1.0.0 dev /home/anirudh/ide
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 94% after seal                                                                    

 ERROR  Failed to compile with 2 errors                                                                                        02:51:08

 error  in (webpack)-dev-server/client?http://localhost:8080

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /home/anirudh/ide/node_modules/webpack-dev-server/client/index.js: 
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

If you want the same configuration as before:

{
  "plugins": [
    // Stage 2
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",

    // Stage 3
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}

If you're using the same configuration across many separate projects,
keep in mind that you can also create your own custom presets with
whichever plugins and presets you're looking to use.

module.exports = function() {
  return {
    plugins: [
      require("@babel/plugin-syntax-dynamic-import"),
      [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
      [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
    ],
    presets: [
      // ...
    ],
  };
};
 (While processing: "/home/anirudh/ide/node_modules/@babel/preset-stage-2/lib/index.js")
    at _default (/home/anirudh/ide/node_modules/@babel/preset-stage-2/lib/index.js:9:9)
    at loadDescriptor (/home/anirudh/ide/node_modules/@babel/core/lib/config/full.js:157:14)
    at cachedFunction (/home/anirudh/ide/node_modules/@babel/core/lib/config/caching.js:32:19)
    at loadPresetDescriptor (/home/anirudh/ide/node_modules/@babel/core/lib/config/full.js:227:63)
    at config.presets.map.descriptor (/home/anirudh/ide/node_modules/@babel/core/lib/config/full.js:72:19)
    at Array.map (<anonymous>)
    at recurseDescriptors (/home/anirudh/ide/node_modules/@babel/core/lib/config/full.js:70:38)
    at loadFullConfig (/home/anirudh/ide/node_modules/@babel/core/lib/config/full.js:100:6)
    at process.nextTick (/home/anirudh/ide/node_modules/@babel/core/lib/transform.js:28:33)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/main.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /home/anirudh/ide/src/main.js: 
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

If you want the same configuration as before:

{
  "plugins": [
    // Stage 2
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",

    // Stage 3
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}

If you're using the same configuration across many separate projects,
keep in mind that you can also create your own custom presets with
whichever plugins and presets you're looking to use.

module.exports = function() {
  return {
    plugins: [
      require("@babel/plugin-syntax-dynamic-import"),
      [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
      [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
    ],
    presets: [
      // ...
    ],
  };
};
 (While processing: "/home/anirudh/ide/node_modules/@babel/preset-stage-2/lib/index.js")
    at _default (/home/anirudh/ide/node_modules/@babel/preset-stage-2/lib/index.js:9:9)
    at loadDescriptor (/home/anirudh/ide/node_modules/@babel/core/lib/config/full.js:157:14)
    at cachedFunction (/home/anirudh/ide/node_modules/@babel/core/lib/config/caching.js:32:19)
    at loadPresetDescriptor (/home/anirudh/ide/node_modules/@babel/core/lib/config/full.js:227:63)
    at config.presets.map.descriptor (/home/anirudh/ide/node_modules/@babel/core/lib/config/full.js:72:19)
    at Array.map (<anonymous>)
    at recurseDescriptors (/home/anirudh/ide/node_modules/@babel/core/lib/config/full.js:70:38)
    at loadFullConfig (/home/anirudh/ide/node_modules/@babel/core/lib/config/full.js:100:6)
    at process.nextTick (/home/anirudh/ide/node_modules/@babel/core/lib/transform.js:28:33)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/main.js
```

Expected Bounty: 500

**Comment by VibhorCodecianGupta** [comment]
@firefinchdev It works perfectly fine on my machine for `npm run dev`
